require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe LocalsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Local. As you add validations to Local, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # LocalsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all locals as @locals" do
      local = Local.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:locals)).to eq([local])
    end
  end

  describe "GET #show" do
    it "assigns the requested local as @local" do
      local = Local.create! valid_attributes
      get :show, {:id => local.to_param}, valid_session
      expect(assigns(:local)).to eq(local)
    end
  end

  describe "GET #new" do
    it "assigns a new local as @local" do
      get :new, {}, valid_session
      expect(assigns(:local)).to be_a_new(Local)
    end
  end

  describe "GET #edit" do
    it "assigns the requested local as @local" do
      local = Local.create! valid_attributes
      get :edit, {:id => local.to_param}, valid_session
      expect(assigns(:local)).to eq(local)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Local" do
        expect {
          post :create, {:local => valid_attributes}, valid_session
        }.to change(Local, :count).by(1)
      end

      it "assigns a newly created local as @local" do
        post :create, {:local => valid_attributes}, valid_session
        expect(assigns(:local)).to be_a(Local)
        expect(assigns(:local)).to be_persisted
      end

      it "redirects to the created local" do
        post :create, {:local => valid_attributes}, valid_session
        expect(response).to redirect_to(Local.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved local as @local" do
        post :create, {:local => invalid_attributes}, valid_session
        expect(assigns(:local)).to be_a_new(Local)
      end

      it "re-renders the 'new' template" do
        post :create, {:local => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested local" do
        local = Local.create! valid_attributes
        put :update, {:id => local.to_param, :local => new_attributes}, valid_session
        local.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested local as @local" do
        local = Local.create! valid_attributes
        put :update, {:id => local.to_param, :local => valid_attributes}, valid_session
        expect(assigns(:local)).to eq(local)
      end

      it "redirects to the local" do
        local = Local.create! valid_attributes
        put :update, {:id => local.to_param, :local => valid_attributes}, valid_session
        expect(response).to redirect_to(local)
      end
    end

    context "with invalid params" do
      it "assigns the local as @local" do
        local = Local.create! valid_attributes
        put :update, {:id => local.to_param, :local => invalid_attributes}, valid_session
        expect(assigns(:local)).to eq(local)
      end

      it "re-renders the 'edit' template" do
        local = Local.create! valid_attributes
        put :update, {:id => local.to_param, :local => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested local" do
      local = Local.create! valid_attributes
      expect {
        delete :destroy, {:id => local.to_param}, valid_session
      }.to change(Local, :count).by(-1)
    end

    it "redirects to the locals list" do
      local = Local.create! valid_attributes
      delete :destroy, {:id => local.to_param}, valid_session
      expect(response).to redirect_to(locals_url)
    end
  end

end
